### PR TITLE
Enable real UE monitoring in UI

### PR DESCRIPTION
**Pull request by PedroDSFerreira**
Dashboard table:
image

New simulated UE modal:
image

New real UE modal:
image

### CODE REVIEW

**Review by rafael-direito — CHANGES_REQUESTED** [review]
The code seems nice.
I just have two suggestions: 

- Given the print screen you provided, it seems the user must tick a check box for the UE to be simulated. In my understanding, the simulation should be the default behavior. Thus, I would rather have the client ticking that check box when he wishes to have a real UE.

- Right below the check box, we could have a description on what it means for a UE to be real. This will allow our clients to better understand what "real data" means. 

Still, overall, great work!

**Comment by PedroDSFerreira** [comment]
How does this look?
image

**Comment by rafael-direito** [comment]
I would use this label: "Consumes real-time location data"
Then, I would have this text as a warning/description: "If this check-box is checked, it means that the created UE will receive live location updates via a message bus. Therefore, no location coordinates will be simulated for this UE."
 
Afterwards, when we finish the process of ingesting real-world data, I would add "More information on this is available at xxx " or something similar.

**Comment by PedroDSFerreira** [comment]
Is this what you had in mind?

image

**Review by rafael-direito — APPROVED** [review]

**Comment by rafael-direito** [comment]
Perfect :ok_hand:

**Pull request merged**
